# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import openapi_client
from openapi_client.paths.api_order_id_status_status_transaction_id_secondary_transaction_id import post  # noqa: E501
from openapi_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestAPIOrderIdStatusStatusTransactionIdSecondaryTransactionId(ApiTestMixin, unittest.TestCase):
    """
    APIOrderIdStatusStatusTransactionIdSecondaryTransactionId unit test stubs
        Update order status  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200










if __name__ == '__main__':
    unittest.main()
